# Generated by Django 5.1.5 on 2025-02-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['id'], 'verbose_name': 'ToDo Item'},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo_list.category'),
        ),
    ]
