# Generated by Django 5.1.5 on 2025-02-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_category_alter_todoitem_options_todoitem_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Categorie'},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
